### PR TITLE
Rawcam

### PR DESCRIPTION
**Pull request by backinside**
I've added all the modes and options I could gather, Mode 1, 2 and 7 works fine
It' accepts some cmd line arguments, to make testing easier
More details and conversation about this patch is here:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=47798&start=75

### CODE REVIEW

**Comment by 6by9** [comment]
A big thanks for doing this :-)

A quick skim looks like it may function.
From a style perspective, it would be a lot cleaner to have all the registers defined in structures, preferably in a header (or even a header per mode), eg:
```
struct ov_mode {
   int width;
   int height;
   const struct sensor_regs *regs[];
  int num_regs;
};
const struct sensor_regs mode1_regs[] = {
  {0x0100, 0x00},
   ...
}
const struct sensor_regs mode2_regs[] = {
  {0x0100, 0x00},
   ...
}
const struct ov_mode modes[] = {
  {
     //ignore mode 0
  },
  {
     // mode 1 1920x1080
     .width = 1920,
     .height = 1080,
     .regs = mode1_regs,
     .num_regs = sizeof(mode1_regs) / sizeof(mode1_regs[0]);
  },
  {
     // mode 2 2592x1944
     .width = 2592,
     .height = 1944,
     .regs = mode2_regs,
     .num_regs = sizeof(mode2_regs) / sizeof(mode2_regs[0]);
  },
//etc
};
```
That avoids any memory allocations and lots of lines of code which is just setting up static data.
Yes you're currently searching the register list and modifying the flips, exposure, and gain, but there's no need. The sensor takes the last value programmed into any register. Remove those settings from each table and add code responsible for each of them. The base value should be consistent in each mode, so just amend as necessary.
Add the 0x0100 register write afterwards.

**Comment by backinside** [comment]
I'll restructure the code in the next version, move the regs in separate files
I'm trying to keep the code as close to the captured data, as possible, and this would actually help a lot
I'm not sure though, whether I should keep the duplicate reg settings in the code, or not.
In the original dumps, I've kept the whole communication, but in the patch request, I've removed the redundant register settings
What do you think?
The flip registers are shared with binning if I understand it correctly, so do you think, I should add mode parameters to the ov_mode struct, and control the binning too?
Or should I read the original value from the sensor_regs?

**Comment by 6by9** [comment]
Be a little careful with removing redundant register writes. 0x01xx in particular are things like reset and sleep mode, so do need to be set and cleared at appropriate points. If it's the 0x3xxx range then those are probably safe.

You can probably see now why there was an I2C read of 0x3820 and 0x3821 in the dumps. Binning and flips do appear to be in the same register. You could add the binning value into the proposed struct ov_mode and just OR it in. 0x3500-2 and 0x350A-B are only used for the one function, so don't worry about the value of any other bits - they will be 0.

Re bitmasking, make life easier for yourself. There's no need to overcomplicate it, as this is code specific to OV5647 anyway.
```
		setReg(0x3502, 0, 7, exposure & createMask(0, 7));
		setReg(0x3501, 0, 7, (exposure & createMask(8, 15)) >> 8);
		setReg(0x3500, 0, 3, (exposure & createMask(16, 19)) >> 16);
```
setReg has changed now anyway if it's not writing into the array of setting. 
Make a new function from
```
unsigned char msg[3];
      *((unsigned short*)&msg) = ((0xFF00&(ov5647[i].reg<<8)) + (0x00FF&(ov5647[i].reg>>8)));
      msg[2] = ov5647[i].data;
      if(write(fd, msg, 3) != 3)
      {
         vcos_log_error("Failed to write register index %d", i);
      }
```
call it something like regWrite(int fd, uint16_t reg, uint8_t val), and then run with
```
regWrite(0x3500, (exposure>>16)&0x03);
regWrite(0x3501, (exposure>>8)&0xFF);
regWrite(0x3502, exposure&0x03);
regWrite(0x350A, (gain>>8)&0x03);
regWrite(0x350B, gain&0xFF);
```
(Reuse regWrite in writing the table of registers too).

Drop the references to jbeale from all apart from the top of the original register set. Git has full history anyway, so an acknowledgement is sufficient. Extra stuff also detracts from the readability.

**Comment by 6by9** [comment]
Squashed and merged as https://github.com/6by9/userland/commit/5472cfde4c661eb0f012beaedda433ee86c8f4ac
Extra changes on top to shape it into a style that will also allow the same code to be reused for imx219 without masses of changes.

Rebased https://github.com/6by9/userland/tree/rawcam to top of raspberrypi/userland.

**Pull request closed without merging**
